### ISSUE TITLE
QuickNES Update request

### ISSUE THREAD

**Issue by ghost** [libretro/docs#58]
# First and foremost consider this:
- Only documentation related issues should be filed here. Not RetroArch bugs, or core bugs, or game bugs, or build errors.
- Before reporting a 404, refresh the doc a few times.

## Documents

Add core option:
No sprite limit ( enable/disable) - Reduce sprite flickering.

### Proposed changes

(no need to write this note, only as a general NES guide when checking compatibility) Note: Changes to compatibility. ROMS has to have the correct header as most rom headers are not verified even with clrmame. Use database like http://bootgod.dyndns.org:7777/ to confirm headers.

Burai Fighter 	Softlocks when entering a level. - confirmed issue MMC3 incompatible.
Crisis Force 	Crashes on start. - playable in latest version. Mapper 23 
Family Circuit '91 	Crashes on start - unsupported mapper 210
Gradius II 	Crashes on start - playable in latest version.Mapper 25
Huge Insect 	No enemies spawn. Mapper 3  confimed issue ( probably due to unemulated bus conflict handling)
Lagrange Point 	Crashes on start - playable in latest version. Mapper 85
Mickey's Safari in Letterland 	Graphical glitches on the sides of the screen and on the status bar. (1)
Ms. Pac-Man (Tengen version) 	Graphical glitches on the sides of the screen. playable Mapper 0 ( rom header issue )
Skull & Crossbones 	Crashes on start. - unsupported mapper.

**Graphical glitches on the sides of the screen** - this kind of issues should be fixed in latest version, assuming rom has correct header. QuickNES should now properly show full 256 width courtesy from Dwedit update.

Thanks

**Comment by CuttleFishJones8652** [comment]
Added the No sprite limit core option here: https://github.com/libretro/docs/pull/53

Adding compatibility info here: https://github.com/libretro/docs/pull/59

- Move the Compatibility section up, now it's right below the Background section.
- Removed Crisis Force, Gradius II, Lagrange Point, Mickey's Safari in Letterland, Ms. Pac-Man from the compatibility table since they got fixed.
- Update info for Burai Fighter, Fmaily Circuit 91, Huge Insect, Skull & Crossbones in compatibility table.

Is this ok?

**Comment by ghost** [comment]
that looks good. ill close this for now till i have things to add.
