### ISSUE TITLE
core Beetle PSX HW RetroArch OpenGL3.3 support

### ISSUE THREAD

**Issue by Grasshopper2023** [libretro/docs#787]
Libreto Docs
https://docs.libretro.com/library/beetle_psx_hw/

Recreate error
download RetroArch Win10 Pro
download core Beetle PSX HW
run PlayStation cue file and it shows error open hardware accelerator not found fallback
to software renderer (openGL 1.1 software only)

I have Lenovo G50 laptop with integrted graphics Intel
I downloaded OpenGL Extensions Viewer 6.3.8.0
OpenGL report shows 100% compablity with OpenGL4.3
Beetle PSX HW needs OpenGL3.3 support

I found from reddit post Beetle PSX HW has never worked with OpenGL.
Only Vulkan driver for Linux has hardware support for OpenGL3.3

Update documentation on:
https://docs.libretro.com/library/beetle_psx_hw/

Source:

https://www.reddit.com/r/RetroArch/comments/7uou6y/psx_beetle_hw_issues_with_opengl/
OnionEclipse
·
5 yr. ago
This might be out dated info but hw has never worked correctly with open gl. If you want hw you need the vulkan driver.

**Comment by hizzlekizzle** [comment]
You may be surprised to hear that a random comment from a random dude on reddit isn't accurate :P

I know the GL renderer definitely worked at some point because I added texture filtering to it first as a proof of concept before adding it to the vulkan renderer.

That said, the GL renderer has more bugs than the vulkan renderer, in general, and it's currently segfaulting for me in linux (dunno what's up there yet, but it's happening even when I build very old snapshots, so it may be something external to the core).

**Comment by gouchi** [comment]
@Grasshopper2023 I think it should be  better to confirm the issue first in the [dedicated repository](https://github.com/libretro/beetle-psx-libretro/issues).

If there is an issue, we will update the documentation accordingly.

Moreover, I made a test and Beetle PSX HW core can be launched using  `glcore` video driver on Linux with Nvidia.

Thank you.

**Comment by Grasshopper2023** [comment]
All good, keep up the spirit and hard work, cheers!

Saadetud rakendusest Outlook Androidile<https://aka.ms/AAb9ysg>
________________________________
